#server
server:
  port: 9020

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orz?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: orz
    password: "{cipher}80f3c8e2c2e28905eb73e60c6cb5640689cb3da3046c0be43ed3db6c464a1b75"
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
  resources:
    add-mappings: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health
