#server
server:
  port: 12021
  servlet:
    context-path: /oauthservice
  use-forward-headers: false

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orz?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: orz
    password: "{cipher}80f3c8e2c2e28905eb73e60c6cb5640689cb3da3046c0be43ed3db6c464a1b75"
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update #validate 
    show-sql: true
  resources:
    add-mappings: false
  freemarker:
    template-loader-path: classpath:/templates
    prefix: /freemarker/
    suffix: .ftl

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:12001/eureka/
        #defaultZone: http://localhost:12001/eureka/, http://localhost:12002/eureka/
        
security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**
  oauth2:
    resource:
      jwt:
        keyValue: abc

management:
  endpoints:
    web:
      exposure:
        include: health
        