#server
server:
  port: 20501

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orz?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: orz
    password: "{cipher}348ea3baefd7516f636f05dc0274fc41e12373733230d2620368c3e5e8ec9b05"
    driver-class-name: com.mysql.cj.jdbc.Driver
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true


#eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:20100/eureka/

